### ISSUE TITLE
Merging Conflicts

### ISSUE THREAD

**Issue by canyurtcu** [UCL-COMP0233-23-24/RSE-Classwork#6]
![image](https://github.com/UCL-COMP0233-23-24/RSE-Classwork/assets/42780564/8fe93583-dff3-4e41-a7a7-54200a88d617)
![image](https://github.com/UCL-COMP0233-23-24/RSE-Classwork/assets/42780564/68af4207-6d69-4f66-aa6e-e4f48d7adf08)
https://github.com/UCL-COMP0233-23-24/RSE-Classwork/issues/4

**Comment by dpshelio** [comment]
You should have posted this and the comment into your [RSE-Classwork fork](https://github.com/canyurtcu/RSE-Classwork/issues) as you did with https://github.com/canyurtcu/RSE-Classwork#1
