### ISSUE TITLE
Generating and Solving conflicts 

### ISSUE THREAD

**Issue by daisy-tseng** [UCL-COMP0233-23-24/RSE-Classwork#7]
<img width="930" alt="Screen Shot 2023-10-17 at 12 43 53 PM" src="https://github.com/UCL-COMP0233-23-24/RSE-Classwork/assets/79133454/3477674f-d34d-45a7-a4df-bee4d8f0c671">

<img width="920" alt="Screen Shot 2023-10-17 at 12 44 24 PM" src="https://github.com/UCL-COMP0233-23-24/RSE-Classwork/assets/79133454/369ad231-b7f1-4983-a5ae-70f75a77ea87">

**Comment by daisy-tseng** [comment]
[Answers UCL-COMP0233-23-24/RSE-Classwork#4](https://github.com/UCL-COMP0233-23-24/RSE-Classwork/issues/4)

**Comment by dpshelio** [comment]
You should have posted this and the comment into your [RSE-Classwork fork](https://github.com/daisy-tseng/RSE-Classwork/issues)
