### ISSUE TITLE
Answers UCL-COMP0233-23-24/RSE-Classwork#4 - Generate and Merge conflicts

### ISSUE THREAD

**Issue by NDiurno94** [UCL-COMP0233-23-24/RSE-Classwork#8]
![Screenshot 2023-10-17 183627](https://github.com/UCL-COMP0233-23-24/RSE-Classwork/assets/146762492/19b0901d-08bf-43bd-8c8f-4679234a34e4)

**Comment by dpshelio** [comment]
You should have posted this into a new issue in your RSE-classwork fork, not in this upstream repository (as you did with NDiurno94/RSE-Classwork#1)
